manzt/juv

pyproject.toml, src/juv/__init__.py, tests/test_juv.py, uv.lock
Migrates CLI parsing to use `click`.
This PR also deprecates the use of top-level `lab`, `notebook`, `nbclassic`
commands and making the parsing of uv's flags more consistent.
Instead, for consistency with `uv`, we prefer `run` with the `--jupyter` flag
to specify a notebook runtime. Users can set their preferences with a
`JUV_JUPYTER` environment variable.
This way juv's CLI is more similar to uv, so learning should be similar. This will
```uv
uv init --script foo.py
uv add --script foo.py anywidget
uv run foo.py
```
```sh
juv init
juv add Untitled.ipynb anywidget
juv run Untitled.ipynb
juv run --jupyter=nbclassic --python=3.4 --with=polars Untitled.ipynb
```
=> feat!: Switch to click CLI

src/juv/_run.py, src/juv/_run_managed.py
Idea from @dvdkouril.
The juptyer-server logs are really verbose and using the `--log-level` flag doesn't do very much in terms of filtering.
The default behavior of `juv run` will be to _replace_ the current process with the one spawned by `uvx <jupyter command>`. However, this PR adds a new enviroment variable `JUV_RUN_MODE=[replace|managed]` that will allow the user to choose between the two modes.
The managed mode will spawn a child process with a consistent but more minimal UI in the terminal.
https://github.com/user-attachments/assets/a63c6d96-bbe5-4fa1-a45c-9d78b607b1c8
We may change the default behavior in the future in a minor release, but for now I'm likely going to be using this myself and we can start iterating on more features for the "managed" mode.
=> feat: Add managed run mode via `JUV_RUN_MODE=managed` env

src/juv/__init__.py, src/juv/_edit.py
Adds `juv edit Untitled.ipynb # [--format=[markdown|py:percent]]`. Uses the default editor or `--editor` for editing the file, writing the contents back out as a notebook.
=> Add `edit` command for quick editing in default editor

src/juv/__init__.py
Prints the contents of the notebook to stdout in either markdown or as a py:percent script.
=> Add `cat` command

src/juv/__init__.py, src/juv/_cat.py, src/juv/_edit.py
The py:percent syntax is harder to resolve and markdown is much more explict. We could bring it back but for now this works.
=> Require editing in markdown for better diffs

pyproject.toml, src/juv/__init__.py, src/juv/_run.py, src/juv/_run_managed.py, tests/test_juv.py
Adds the ability to pass down subcommand arguments to underlying jupyter frontend:
```sh
juv run Untitled.ipynb -- --no-browser
```
The subcommand arguments follow the `--` separator and are not parsed by the `juv` command itself.
This PR also adds a `JUV_DEBUG` flag, which in tests will just print the uv command to the CLI instead of running it.
=> Support forwarding flags to underlying Jupyter front end

src/juv/__init__.py, src/juv/_add.py, src/juv/_init.py, tests/test_juv.py
Supports using the `--extra` flag for `add`.
Include optional dependencies from the specified extra name.
May be provided more than once.
```sh
juv add Untitled.ipynb --extra dev anywidget # adds `anywidget[dev]`
```
=> Support `add --extra`

src/juv/__init__.py, src/juv/_add.py, src/juv/_init.py, tests/test_juv.py
Adds the `--editable` flag to `add` to the requirements as editable (e.g., a local package).
```sh
juv add Untitled.ipynb --editable ./path/to/package
```
=> Support `--editable` sources for `add`

src/juv/_exec.py, src/juv/_run.py
Since we now pipe the contents of the script into uv via `stdin` we need to change directories to the directory with the script to resolution of inline metadata is resolved correctly.
=> Change directories prior to running uv

src/juv/__init__.py, src/juv/_clear.py
Adds `--check` flag to `juv clear` to assert cell execution count and output are empty. Useful for CI/CD pipelines.
=> Add `--check` flag for `juv clear`

src/juv/_run_template.py
Fixes #42
Prefers using a user data dir over $TMPDIR, which could be on a different device. I suppose we could still use symbolic links instead of hard links (or copy files if we can't hardlink) but this should be most performant.
=> Use managed temp dir for JUPYTER_DATA_DIR

src/juv/__init__.py, src/juv/_cat.py, src/juv/_edit.py, uv.lock
This PR introduces a `--pager` flag to the juv cat command, allowing users to specify a custom pager tool for displaying the notebook’s contents. If the `--pager` flag is not provided, juv cat will default to the `JUV_PAGER` environment variable (if set).
When `JUV_PAGER` (or `--pager`) is set to `bat`, additional flags are automatically added to improve formatting, including syntax highlighting with an inferred file type based on notebook content (e.g., markdown or script).
This setup achieves the same effect as manually piping to bat if installed:
```sh
juv cat Untitled.ipynb | bat --language md --file-name 'Untitled.md'
```
or
```sh
juv cat Untitled.ipynb --script | bat --langugage py --file-name 'Untitled.py'
```
=> Add `--pager` flag for `juv cat`

src/juv/__init__.py, src/juv/_add.py, tests/test_juv.py
Adds a `--pin` flag to `juv add` to resolve packages to a specific version. This will effectively pin the package in the notebook/script to whatever the resolver finds at the time of the command.
Works with both scripts and notebooks.
```sh
uvx juv init
uvx juv add Untitled.ipynb numpy polars --pin # adds numpy==2.1.3 polars==1.13.1
```
```sh
uv init --script foo.py
uvx juv add foo.py numpy polars --pin
```
=> Add `--pin` flag for `juv add`

src/juv/_nbutils.py, tests/test_juv.py
Adds default `kernelspec` metadata when initializing notebooks
=> Add kernelspec metadata to new notebooks

src/juv/_run_replace.py, src/juv/_run_template.py, tests/test_juv.py
I only had to make a few code tweaks to get the code working on my windows box for firing up the subprocess, and I added raw string syntax for the notebook path in case the notebook's path has a \t in it so it doesnt change the \t into a tab. or a \u into a unicode escape etc.  and I added `ignore_cleanup_errors=True` to all the tempdirectory usage because without it, an error would throw anytime I shutdown jupyterlab because the nbsignatures.db of jupyter was locked.
To get the tests to pass I had to replace the pipes at the end of some of the lines with the pipe symbol from my keyboard (I'm not going to pretend to be an encoding expert, but when I did a find/replace on the pipe symbols in the existing code with the pipe symbol on my keyboard, magically the tests passed for me)
let me …
=> Support windows with `juv run`

pyproject.toml, src/juv/__init__.py, src/juv/_lock.py, tests/test_juv.py, uv.lock
Adds the `juv lock` subcommand to lock the scripts dependencies as a `uv.lock` format.
```sh
juv lock Untitled.ipynb
```
Currently, this just creates `"uv.lock"` key in the notebook metadata with the contents of the generated lockfile. We will need to update other commands to respect (and update this metadata) if it exists accordingly.
=> Add `lock` command

src/juv/_add.py, tests/test_juv.py
If a notebook is locked (e.g., via `juv lock Untitled.ipynb`), the add
command now updates the existing lockfile to ensure consistency.
=> Sync lockfile during `add` command

src/juv/_remove.py, tests/test_juv.py
If a notebook is locked (e.g., via `juv lock Untitled.ipynb`), the
`remove` command now updates the existing lockfile to ensure
consistency.
=> Sync lockfile during `remove` command

src/juv/_run.py, src/juv/_run_managed.py, src/juv/_run_replace.py, src/juv/_run_template.py, tests/test_juv.py
See
- #64 
- #65 
- #66 
The `run` command now detects the presence of a lockfile and will run the notebook in a locked enviroment.
TODO:
=> Respect lockfile in `run`

src/juv/__init__.py, src/juv/_add.py, src/juv/_remove.py, src/juv/_tree.py, src/juv/_uv.py, tests/test_juv.py
Show notebook dependencies as a tree:
```sh
juv init
juv add Untitled.ipynb anywidget
juv tree Untitled.ipynb
```
=> Add `tree` command to list notebook dependencies

src/juv/__init__.py, src/juv/_lock.py, tests/test_juv.py
Clears lockfile metadata from the Jupyter notebook with the addition of
the `--clear` to the command.
=> Add `--clear` flag to `lock` to clear lockfile metadata

src/juv/__init__.py, src/juv/_export.py, src/juv/_init.py, src/juv/_uv.py, src/juv/_venv.py
Alternative to #62 
Some editors and enviroments are missing the benefits from `juv` standalone notebooks, simply because we don't make it easy to _use_ the specified virutal enviroment outside of spawning a Jupyter runtime with `juv run`.
While we typically try to hide virtual environments, they remain crucial for ecosystem like language servers, autocomplete, and intellisense, and exposing some way to quickly make a notebok enviroment is the easiest way to bring `juv` standalone notebooks to unknown tools.
To improve compatibility with more editors and tools, this PR introduces:
```sh
juv venv --from=Untitled.ipynb
```
This command creates a virtual environment with the dependencies and locking behavior expected from `juv`, and adds `ipykernel` for running the notebook. The resulting …
=> Add `juv venv` to support exporting explicit notebook enviroments

src/juv/__init__.py, src/juv/_venv.py
Allows for passing a script with inline script metadata to `juv venv`.
```sh
uv init --script foo.py
uv add --script foo.py attrs
juv venv --from=foo.py
```
Useful for quickly creating a `.venv` for a standalone script, which can be
used by other tools like text editors or IDEs.
=> Extend venv export to standalone scripts as well

pyproject.toml, src/juv/__init__.py, src/juv/_uv.py, src/juv/_venv.py, uv.lock
Needs:
- https://github.com/astral-sh/uv/issues/12145
`uv sync --script` has the real behavior that we want with the addition that it intelligently updates an existing environment instead of deleting and creating from scratch.
We should probably just rename the original command (making venv an alias) to align with `uv`.
This is a **breaking** change because it bumps uv's lower bound to v0.6.7.
=> Replace `juv venv` internals with `uv sync --script`

pyproject.toml, src/juv/_run_template.py, src/juv/static/setup.py, tests/test_e2e.py, tests/test_juv.py
Centralizes logic for setting up Jupyter data/config dirs, writing
`uv.lock` to notebook metadata, and cleaning up temp files into
`static/setup.py`. Simplifies template generation in `_run_template.py`
by injecting shared setup script.
Also the setup code is now type-checked and formatted.
=> Move `juv run` Jupyter setup logic to static module

src/juv/static/setup.py
This PR simplifies how we set up Jupyter paths in `juv run` and _should_ hopefully fix (#61). 
Instead of creating a merged directory of Jupyter data files, we now just set `JUPYTER_PATH` and `JUPYTER_CONFIG_PATH` directly based on what's available in the current virtual environment. This works better across platforms and avoids the complexity of copying, linking, deleting files. 
I _think_ what is happening on Windows is that we weren’t correctly identifying the virtual environment root. Unix and Windows place `site-packages` at different depths, so the old logic would go up three levels regardless. Now we handle each case explicitly, which should make path resolution more reliable.
```sh
<venv>/lib/pythonX.Y/site-packages/
<venv>/share/jupyter/
<venv>/etc/jupyter/ …
```
=>  Correctly resolve Jupyter data/config dirs on Windows
